GenerationApp/GenerationApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^', include(('generation_app.urls', 'generation_app'), namespace='generation_app')),
    url(r'^admin/', admin.site.urls),

]

GenerationApp/generation_app/urls.py
from django.conf.urls import url
from django.urls import path
from .views import ScenarioPageView
from . import views

urlpatterns = [
    path('scenario/', ScenarioPageView.as_view(), name='scenario'),
    url(r'^$', views.index, name='index'),
    url(r'^start/$', views.start, name='start'),
    url(r'^stop/$', views.stop, name='stop'),
]

GenerationApp/generation_app/models.py
from django.db import models

GenerationApp/generation_app/views.py
from django.shortcuts import render, redirect
import threading
from generation_app.IOCGenerator.thread import IoCThread
from . import settings as s
from django.views.generic import TemplateView


class ScenarioPageView(TemplateView):
    template_name = 'GenerationApp/scenario.html'


# function rendering requested index page of generation app
def index(request):
    return render(request, 'GenerationApp/index.html')


# start requested IoC thread if it exists
def start(request):
    ioc_gen_id = request.POST['ioc_gen_id']
    if ioc_gen_id != '':
        ioc_gen = s.ioc_dict.get(ioc_gen_id, '')
        if ioc_gen != '':
            thread = IoCThread(name=ioc_gen_id, iocgenerator=ioc_gen, interval=3)
            thread.start()
            thread.status = 1
        else:
            print('Requested IoC doesn\'t exists.')
    else:
        print('Empty request')
    return redirect('generation_app:index')


# if there are no active threads, redirect to index page right away
# otherwise stop the requested IoC_thread and its status if it exists
def stop(request):
    active_thread_list = threading.enumerate()
    empty_thread_list = len(active_thread_list) <= 0
    if not empty_thread_list:
        ioc_gen_id = request.POST['ioc_gen_id']
        if ioc_gen_id != '':
            for t in active_thread_list:
                if t.getName() == ioc_gen_id:
                    t.status = 0
                    t.stop = 1
        else:
            print('Empty input')

    return redirect('generation_app:index')

GenerationApp/templates/GenerationApp/base.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'generation_app/style.css' %}">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{%  block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand" href="#">Generation App |</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Indicators of Compromise</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/scenario">Scenario's</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

GenerationApp/templates/GenerationApp/index.html
{% extends "GenerationApp/base.html" %}
{% load staticfiles %}
{% block content %}
    <head>
        <title>Indicators of compromise</title>
    </head>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <table class="table table-hover">
                    <thead>
                    <tr align="center">
                        <th scope="col">#</th>
                        <th scope="col">Indicator of Compromise Type</th>
                        <th scope="col">Start</th>
                        <th scope="col">Stop</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr align="center">
                        <th scope="row">1</th>
                        <td>Traffic Generator</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">2</th>
                        <td>Foreign country</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_2" name="ioc_gen_id" value=2>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_2" name="ioc_gen_id" value=2>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">3</th>
                        <td>DNS</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_3" name="ioc_gen_id" value=3>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_3" name="ioc_gen_id" value=3>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">4</th>
                        <td>SSH</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_4" name="ioc_gen_id" value=4>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_4" name="ioc_gen_id" value=4>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">5</th>
                        <td>Denial of Service</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_5" name="ioc_gen_id" value=5>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_5" name="ioc_gen_id" value=5>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">6</th>
                        <td>IRC</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_6" name="ioc_gen_id" value=6>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_6" name="ioc_gen_id" value=6>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

GenerationApp/templates/GenerationApp/scenario.html
{% extends "GenerationApp/base.html" %}
{% load staticfiles %}
{% block content %}
    <head>
        <title>Scenario's</title>
    </head>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover">
                    <thead>
                    <tr align="center">
                        <th scope="col">#</th>
                        <th scope="col">Scenario</th>
                        <th scope="col">Start</th>
                        <th scope="col">Stop</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr align="center">
                        <th scope="row">1</th>
                        <td>Botnet infection</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">1</th>
                        <td>Phishing attack</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">1</th>
                        <td>Brute-force attack</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    <tr align="center">
                        <th scope="row">1</th>
                        <td>Keylogger infection</td>
                        <td>
                            <form action="{% url 'generation_app:start' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="start_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-success">Start</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'generation_app:stop' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="stop_1" name="ioc_gen_id" value=1>
                                <button type="submit" class="btn btn-danger">Stop</button>
                            </form>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}