DetectionApp/DetectionApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
urlpatterns = [
    url(r'^', include(('detection_app.urls', 'detection_app'), namespace='detection_app')),
    path('admin/', admin.site.urls),
]

DetectionApp/detection_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detectiontool/$', views.detection_tool_overview, name='detectiontool_overview'),
    url(r'^detectiontool/(?P<detectiontool_id>[0-9]+)/$', views.detectiontool, name='detectiontool'),
    url(r'^detectiontool/(?P<detectiontool_id>[0-9]+)/whitelist/(?P<operation>.+)/$', views.detection_tool_access_list_change, name='whitelist'),
]

DetectionApp/detection_app/models.py
from django.db import models



# Create your models here.
class Packet(models.Model):
    src_ip = models.CharField(default='0.0.0.0', max_length=30)
    dst_ip = models.CharField(default='0.0.0.0', max_length=30)
    src_port = models.CharField(default='0', max_length=30)
    dst_port = models.CharField(default='0', max_length=30)
    content = models.CharField(default='', max_length=1000)
    rcv_date = models.DateTimeField(auto_now_add=True)
    checked = models.BooleanField(default=False)
    flagged = models.BooleanField(default=False)

    class Meta:
        get_latest_by = 'rcv_date'
        ordering = ['rcv_date']

    def format_string(self):
        variable_string = {"src_ip": self.src_ip, "dst_ip": self.dst_ip, "src_port": self.src_port, "dst_port": self.dst_port}
        return variable_string

    def __str__(self):
        return self.src_ip+":"+self.src_port+"  =>  "+self.dst_ip+":"+self.dst_port


class PacketFlag(models.Model):
    packet_id = models.ForeignKey(Packet, on_delete=models.CASCADE)
    flag_type = models.IntegerField(null=True, default=0, blank=True)
    flagged_reason = models.CharField(null=True, default='', max_length=200, blank=True)


class DetectionTool(models.Model):
    id = models.IntegerField(primary_key=True)
    tool_name = models.CharField(default="detection tool", max_length=30)
    whitelistable = models.BooleanField(default=False)

    def __str__(self):
        return self.tool_name


class AccessList(models.Model):
    detection_tool_id = models.ForeignKey(DetectionTool, on_delete=models.CASCADE)
    access_list_item = models.CharField(default='0.0.0.0', max_length=30)

    class Meta:
        ordering = ['access_list_item']
        unique_together = (("detection_tool_id", "access_list_item"),)

DetectionApp/detection_app/forms.py
from django import forms


class WhitelistChanceForm(forms.Form):
    post = forms.CharField

DetectionApp/detection_app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Packet, DetectionTool, PacketFlag, AccessList
from .forms import WhitelistChanceForm


def index(request):
    latest_packets_list = reversed(Packet.objects.order_by('-rcv_date')[:10])
    latest_flagged_packets_list = reversed(PacketFlag.objects.order_by('-packet_id__rcv_date')[:10])
    detection_tool_list = DetectionTool.objects.all()
    detection_tool_name_list = {}
    for tool in detection_tool_list:
        detection_tool_name_list[tool.id] = tool.tool_name

    context = {'latest_packets_list': latest_packets_list,
               'latest_flagged_packets_list': latest_flagged_packets_list,
               'detection_tool_list': detection_tool_name_list}
    return render(request, 'detection_app/index.html', context)


def detectiontool(request, detectiontool_id):
    form = WhitelistChanceForm()
    tool = get_object_or_404(DetectionTool, pk=detectiontool_id)
    latest_flagged_packets_list = reversed(
        PacketFlag.objects.filter(flag_type=detectiontool_id).order_by('-packet_id__rcv_date')[:10])
    access_list = AccessList.objects.filter(detection_tool_id_id=detectiontool_id).order_by('access_list_item')

    return render(request, "detection_app/detectiontool.html",
                  {'detection_tool': tool, 'latest_flagged': latest_flagged_packets_list, 'whitelist': access_list,
                   'form': form})


def detection_tool_access_list_change(request, detectiontool_id, operation):
    if operation == 'add':
        tool = get_object_or_404(DetectionTool, pk=detectiontool_id)
        AccessList.objects.get_or_create(
            detection_tool_id=tool,
            access_list_item=request.POST['access_list_item'],
        )
    elif operation == 'remove':
        try:
            access_list_item = AccessList.objects.get(detection_tool_id_id=detectiontool_id, access_list_item=request.POST['access_list_item'])
            access_list_item.delete()
        except AccessList.DoesNotExist:
            pass
        except AccessList.MultipleObjectsReturned:
            pass

    return redirect('detection_app:detectiontool', detectiontool_id=detectiontool_id)


def detection_tool_overview(request):
    return render(request, "detection_app/detection_tool_overview.html")

DetectionApp/templates/detection_app/base.html
{% load staticfiles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'detection_app/style.css' %}">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{%  block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Detection App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/detectiontool/1">DNS Tool</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/detectiontool/2">Foreign Countries Tool</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/detectiontool/3">SSH Tool</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}
{% block content %}
{% endblock %}
{% block whitelist %}
{% endblock %}
</body>
</html>

DetectionApp/templates/detection_app/detection_tool_overview.html
{% extends "detection_app/base.html" %}
{% block content %}
<p>Dit is het detectie overview</p>
{%  endblock %}

DetectionApp/templates/detection_app/detectiontool.html
{% extends "detection_app/base.html" %}
{% load staticfiles %}
{% block content %}
<div>
    <table id="table3">
        <caption>The last 10 flagged IP Packets for {{ detection_tool.tool_name }}</caption>
        <tr>
            <th scope="col">Source IP</th>
            <th scope="col">Destination IP</th>
            <th scope="col">Source Port</th>
            <th scope="col">Destination Port</th>
            <th scope="col">Received Time</th>
            <th scope="col">Flagged Reason</th>
            {% if detection_tool.whitelistable %}
                <th scope="col">Whitelist?</th>
            {% endif %}
        </tr>
        {% for flagged in latest_flagged %}
            <tr>
                <td>{{flagged.packet_id.src_ip }}</td>
                <td>{{flagged.packet_id.dst_ip }}</td>
                <td>{{flagged.packet_id.src_port }}</td>
                <td>{{flagged.packet_id.dst_port}}</td>
                <td>{{flagged.packet_id.rcv_date|date:'Y-m-d H:i'}}</td>
                <td>{{flagged.flagged_reason}}</td>
                {% if detection_tool.whitelistable %}
                    <td>
                        <form action="{% url 'detection_app:whitelist' detectiontool_id=detection_tool.id operation='add'%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" id="access_list_item" name="access_list_item" value="{{flagged.packet_id.dst_ip}}">
                            <button type="submit" class="btn btn-success">Add</button>
                        </form>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}
{% block whitelist %}
    {% if detection_tool.whitelistable %}
        <div>
            <table id="table4">
                <caption>The whitelist of {{ detection_tool.tool_name }}</caption>
                <tr>
                    <th scope="col" style="width: 80%">Whitelist</th>
                    <th scope="col" style="width: 20%">Delete?</th>
                </tr>
                {% for item in whitelist %}
                    <tr>
                        <td>{{item.access_list_item}}</td>
                        <td>
                            <form action="{% url 'detection_app:whitelist' detectiontool_id=detection_tool.id operation='remove'%}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="access_list_delete_item" name="access_list_item" value="{{item.access_list_item}}">
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}
{%  endblock %}

DetectionApp/templates/detection_app/index.html
{% extends "detection_app/base.html" %}
{% load staticfiles %}
{% load indextags %}
{% block content %}
<div>
    <table id="table1" style="float: left;width: 49%">
        <caption>The last 10 IP Packets</caption>
        <tr>
            <th scope="col">Source IP</th>
            <th scope="col">Destination IP</th>
            <th scope="col">Source Port</th>
            <th scope="col">Destination Port</th>
            <th scope="col">Received Time</th>
        </tr>
        {% for packet in latest_packets_list %}
            <tr>
                <td>{{packet.src_ip }}</td>
                <td>{{packet.dst_ip }}</td>
                <td>{{packet.src_port }}</td>
                <td>{{packet.dst_port}}</td>
                <td>{{packet.rcv_date|date:'Y-m-d H:i'}}</td>
            </tr>
        {% endfor %}
    </table>
    <table id="table2" style="float: right;width: 49%;">
        <caption>The last 10 flagged IP Packets</caption>
        <tr>
            <th scope="col">Source IP</th>
            <th scope="col">Destination IP</th>
            <th scope="col">Source Port</th>
            <th scope="col">Destination Port</th>
            <th scope="col">Received Time</th>
            <th scope="col">Flagged by</th>
        </tr>
        {% for flagged in latest_flagged_packets_list %}
            <tr>
                <td>{{flagged.packet_id.src_ip }}</td>
                <td>{{flagged.packet_id.dst_ip }}</td>
                <td>{{flagged.packet_id.src_port }}</td>
                <td>{{flagged.packet_id.dst_port}}</td>
                <td>{{flagged.packet_id.rcv_date|date:'Y-m-d H:i'}}</td>
                <td>{{detection_tool_list|get:flagged.flag_type}}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}